### ISSUE TITLE
chRat - about page

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-project#1]
## Value Proposition

As a user
I need to open the about page
to be able to read them

## Description
My hamburger menu need an second button to navigate to aboutpage.
<img width="250px" alt="hamburger menu logged out" src="https://user-images.githubusercontent.com/55069641/179233162-82fa6090-99df-491f-a1cc-a26c4726c91e.png" />
<img width="250px" alt="about and imprint" src="https://user-images.githubusercontent.com/55069641/179494799-a8bc8257-850b-4296-9018-0998c3bc8f4f.png" />

## Acceptance Criteria

Hamburger-menu:
- [x] 1 button to open about within the hamburger menu

Aboutpage:
- [x] textfield
- [x] implement hamburger menu

## Tasks

(for developers team)

- [x] create aboutpage
- [x] 1 button to open about within the hamburger menu
- [x] the backbutton navigate to the mainpage
- [x] implement hamburger menu on aboutpage
- [x]  look at accessibility !

**Comment by PReichetanz** [comment]
Does the back button navigates back to the last visited page (which might be the imprint page) or to the chat page every time?
