### ISSUE TITLE
chRat - autoscroll

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-project#12]
## Value proposition

**As a** user,
**I want to** read the latest message direct without scroll down
**so that** I don't have to scroll

## Acceptance criteria

- [x] all new messages are on top of the latest
- [x] they have to scroll down to the message automaticly

## Complexity

Medium

## Tasks

- [x] implement auto scroll down function

**Comment by PReichetanz** [comment]
Some grammar: It's "latest", not "newest", and "I don't have to scroll...at the bottom"

Questions for acceptance criteria:
1. What do you mean by "last and [newest] latest message is readable"? Only the last two messages? Where are the others? How can I display them?
2. Who is "they", the user?

**Comment by chris-yooo** [comment]
changed :)

**Comment by PReichetanz** [comment]
> Some grammar: It's "latest", not "newest", and "I don't have to scroll...at the bottom"
> 
> Questions for acceptance criteria:
> 
>     1. What do you mean by "last and [newest] latest message is readable"? Only the last two messages? Where are the others? How can I display them?
> 
>     2. Who is "they", the user?

The "..." meant that you adjust the text in between on your own 🙈
