### ISSUE TITLE
chRat - date format

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-project#18]
## Value proposition

**As a** user
**I want to** read the date as a human
**so that** i can read it

## Acceptance criteria

- [x] date in a good format like dd.MM.YYYY HH:MM
- [x] not this one:    2022-08-16T12:23:39.857+00:00   ...

## Complexity

Medium

## Tasks

- [x] date replace func implement to chat
