### ISSUE TITLE
chRat - database

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-project#2]
## Value Proposition

As a user
I need a database
to be able to use the app without fake data

## Description

I have to change the fakedatas into real data and connect all inputs and outputs to mongoDB.

## Acceptance Criteria

- [x] i can write messages that are displayed later in the mainpage
- [x] i can see old messages that are writed in the Mainpage

## Tasks

(for developers team)
- [x] connect the mainpage output with mongoDB
- [x] connect the mainpage message input function wit mongoDB
- [x] use effect to display the chat messages
- [x] implement the mongoDB
