### ISSUE TITLE
chRat - registerpage

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-project#3]
## Value Proposition

As a User
I need to register
to be able to login

## Description

- You got no account information -> yeah now we can register our own login credentials.
- The loginpage become a register button
<img width="250px" alt="Registerpage" src="https://user-images.githubusercontent.com/55069641/179463523-e0d4bca2-2ff0-4795-9a57-dd34d8a8b49e.png" />
- when you click on it the register page appears

<img width="250px" alt="Registerpage" src="https://user-images.githubusercontent.com/55069641/179500454-d3df7fa3-66bc-4b52-af1f-3091dda4bcc1.png" />

- here you must input a username and a password
- with a click on submit your datas are send to the app and you navigate automated back to the loginpage

## Acceptance Criteria

Loginpage:
- [ ] 1 register button thats switch to the register site

Registerpage:
- [ ] 2 input fields -> username input | password input
- [ ] 1 button to submit data

## Tasks

- [ ] 1 button with function to navigate to registerpage
- [ ] create registerpage
- [ ] 2 input fields username and password
- [ ] both inputs are required!
- [ ] 1 submit button to submit the logincredentials

**Comment by PReichetanz** [comment]
Hi Chris,

the description is not clear: Is the user currently at the login or the register page? There seems to be no difference.
- What about required inputs?
- What is the submit button for register?
- What happens after clicking the submit button? Is there a message that the registration worked? To which page is the user navigate? You can add the answer in your description via the wireframe.

**Comment by chris-yooo** [comment]
updated
