### ISSUE TITLE
chRat - logout button

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-project#4]
## Value Proposition

As a User
I need to logout when i am logged in

## Description

- a little adjustement is when you logged in the hamburger menu have to be become 1 more button to logout.
<img width="250px" alt="hamburger menu logged in" src="https://user-images.githubusercontent.com/55069641/179234499-032f40f2-7565-4923-93e9-375879ab4dbf.png" />

## Acceptance Criteria

- [ ] logout button in the hamburger menu
- [ ] shows only when your logged in
- [ ] when you click on it you pageflipped to loginpage

## Tasks

(for developers team)

- [ ] create an logout button
- [ ] navigate function to loginpage
