### ISSUE TITLE
chRat - loginpage

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-project#5]
## Value Proposition

As a user
I need to login
to be able to chat

## Description

- When you connect to my homepage you now should log in before the actual mainpage shows up.
<img width="250px" alt="Loginpage" src="https://user-images.githubusercontent.com/55069641/179353299-4cfa6506-c655-4f85-b2fc-3b1ba3c8874d.png" />

## Acceptance Criteria

There are come edgecases and criteria for the login:

Loginpage:
- [ ] 2 input fields -> username input | password input
- [ ] username are req.
- [ ] password are req.
- [ ] whitesspaces are not allowed/work
- [ ] special characters are note allowed/work
- [ ] only letters in upper and lower case are allowed and work
- [ ] 1 login button

## Tasks

(for developers team)

- [ ] create loginpage
- [ ] create an array with objects these are to represent testlogins
- [ ] 1 input username with criterias from Acceptance Criteria
- [ ] 1 input password with criterias from Acceptance Criteria
- [ ] 1 button with function to login with credentials from input fields
- [ ] look at accessibility!

**Comment by PReichetanz** [comment]
Hi Chris,

some thoughts about the Login:
- What happens if I use the incorrect username / password?
- How often am I allowed to try? Is there a limitation at all or do you implement it later?
- Please be more precise regarding the acceptance criteria (i.e., use sentence to better describe them).
