### ISSUE TITLE
chRat - imprint page

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-project#6]
## Value Proposition

As a user
I want to open a hamburger menu at the bottom
to navigate to a new page imprint

## Description

- my hamburger menu appears at the bottom on every page.
- In it i got a button to navigate to a new page with "imprint" content.
<img width="250px" alt="hamburger menu logged out" src="https://user-images.githubusercontent.com/55069641/179496848-b1e8b379-586b-41bb-81dc-a14ca9760616.png" />
<img width="250px" alt="about and imprint" src="https://user-images.githubusercontent.com/55069641/179496241-a934376e-e27b-4776-8005-e24beb72cd0d.png" />
<img width="250px" alt="about and imprint" src="https://user-images.githubusercontent.com/55069641/179499005-7542ebb0-7f9a-4bc2-87f6-163ed12dec22.png" />

## Acceptance Criteria

Hamburger-menu:
- [x] the menu with sticky at the bottom
- [x] the possibility to open it and close it
- [x] 1 button to open imprint within the hamburger menu

Imprintpage:
- [x] textfield
- [x] implement hamburger menu

Mainpage:
- [x] implement hamburger menu

## Tasks

(for developers team)

- [x] create imprint page
- [x] create the hamburger menu
- [x] implement hamburger menu on mainpage and imprintpage
- [x] possibility to open it and close it
- [x] 1 button to close the hamburger menu
- [x] look at accessibility !
- [x] 1 button to open the page "imprint"
- [x] the backbutton navigate to the mainpage
- [x] implement routing/navigate function

**Comment by PReichetanz** [comment]
Hi Chris,

Just one thing: I would suggest to separate the imprint and about page from each other and create two small user stories. The title of both stories should be like the page, e.g. "About page" and "Imprint page", because the hamburger menu is not a feature for itself, but necessary for these pages.

**Comment by chris-yooo** [comment]
ok but i will let the hamburger menu here in this story in, and open a new story with the about page maybe. ty

**Comment by chris-yooo** [comment]
https://github.com/chris-yooo/capstone-project/issues/1 here the littlerer step :D
