### ISSUE TITLE
chRat - mainpage

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-project#7]
## Value Proposition

As a user
I want to send message's
to be able to read them

## Description

<img width="250px" alt="Mainpage" src="https://user-images.githubusercontent.com/55069641/179478254-b6ac04e2-74b2-455c-a86e-5aaa06f62d44.png" />

## Acceptance Criteria

Maincontent/Chatpage:
- [x] new messages added below
- [x] 1 input field -> to submit messages in the message pool
- [x] 1 button to submit message
- [x] the input field cannot be empty
- [x] after send the form have to empty again

## Tasks

(for developers team)

- [x] global styles
- [x] create main chat content page
- [x] design little chat windows that are displayed in the "chatbox" (new chat windows added below)
- [x] 1 input field with message
- [x] 1 button to submit the message
- [x] look at accessibility !
- [x] add to App

**Comment by PReichetanz** [comment]
Hi Chris,

nice work for this user story! 

- First of all: This won't be your first story, because the user cannot use it: after submitting, nothing happens, because you don't have another page.
- Your first story could be an input field for a text message and an area where these data are displayed after submitting.
- You can use this story later, so you have really good fundamentals as soon as you need a login 🎉

💬 Anyways, let's discuss some issues which came to my mind regarding this story:

## Description
- What is the hamburger menu at the bottom is used for?
- There need to be a wireframe what happens after pressing the Login button.
- Additionally, what happens if the username or password are incorrect?
  - You don't need to answer this right now, just postpone this story and refactor it as soon as you really need a login.

## Acceptance criteria
- I guess both inputs are required? Please state this here.
